#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

cd "$(dirname "$0")"

echo "Running frontend tests (Vitest)..."
(npx vitest --changed) || exit 1

echo "Running backend tests (Jest)..."
(cd ../../back-end &&  npx jest --onlyChanged --bail --cache) || exit 1

npx lint-staged
