name: Frontend & Backend Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: front-end
        run: npm ci

      - name: Run frontend tests (Vitest)
        working-directory: front-end
        run: npx vitest run --environment jsdom --run --reporter=default
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache backend node_modules
        uses: actions/cache@v3
        with:
          path: back-end/node_modules
          key: backend-${{ runner.os }}-node-${{ hashFiles('back-end/package-lock.json') }}
          restore-keys: backend-${{ runner.os }}-node-

      - name: Install backend dependencies
        working-directory: back-end
        run: npm ci

      - name: Run backend tests (Jest)
        working-directory: back-end
        run: npx jest --ci --bail --reporters=default
  deploy:
    name: Deploy to Firebase
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: front-end
      - name: Build Frontend
        run: npm run build
        working-directory: front-end
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Create Deployment Record
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          environment-url: https://bing-bong-77845.web.app/
          description: Firebase hosting deployment